stages: [build, test, deploy]

variables:
  JEKYLL_ENV: production
  BUNDLE_PATH: vendor/bundle

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/bundle

build:
  stage: build
  image: ruby:3.2
  script:
    - gem install bundler
    - bundle config set path "$BUNDLE_PATH"
    - bundle install
    - bundle exec jekyll build --destination _site
  artifacts:
    paths:
      - _site
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH

html_proof:
  stage: test
  image: ruby:3.2
  dependencies: [build]
  script:
    - gem install bundler
    - bundle config set path "$BUNDLE_PATH"
    - bundle install
    - bundle exec htmlproofer ./_site --disable-external
  rules:
    - if: $CI_COMMIT_BRANCH

deploy:
  stage: deploy
  image: ruby:3.2
  dependencies: [build]
  script:
    - gem install bundler
    - bundle config set path "$BUNDLE_PATH"
    - bundle install
    - bundle exec s3_website push
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
